#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

# this is a global configuration file
# no options are overridden here

# Core configuration
spring.application.name: spring-web-jpa-concurrency
server.port: ${SERVER_PORT:8080}
spring.profiles:
  default: default
  active: dev

## Swagger configuration
# https://springdoc.org/properties.html
springdoc:
  show-actuator: true
  swagger-ui:
    use-root-path: true

# Database configuration
spring.datasource:
  url: jdbc:mysql://${MYSQL_SERVER:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:payments}
  username: ${MYSQL_USER:payments}
  password: ${MYSQL_PASSWORD:payments}
  driver-class-name: com.mysql.cj.jdbc.Driver
