#
# https://docs.spring.io/spring-boot/docs/current/reference/html/appendix-application-properties.html
#

## @Overrides: default
# JPA configuration
spring.jpa:
  open-in-view: false
  show-sql: true
  ## Hibernate native properties
  properties.hibernate:
    format-sql: true
    use_sql_comments: true
    generate_statistics: true
    id.new_generator_mappings: true

## @Overrides: default
# DB Initialization Strategy
spring.jpa.generate-ddl: false
spring.jpa.hibernate.ddl-auto: update
spring.sql.init.mode: never

# Core configuration
spring.threads.virtual.enabled: true

# Database configuration
## HikariCP configuration
spring.datasource:
  hikari.transaction-isolation: TRANSACTION_READ_COMMITTED

# Docker configuration
spring.docker.compose:
  file: docker-compose.dev.yaml
  profiles.active: dev

# Logging configuration
logging.level:
  web: DEBUG
  sql: DEBUG
